### ISSUE TITLE
Frontend - Enviar código de verificação de acesso - web

### ISSUE THREAD

**Issue by nickmoura** [RoutinelyOrganization/routinely-web#1]
https://docs.google.com/document/d/10EYyCE27JLvWk0_skOfzLOQ9K01wVXQ0/edit

**Comment by dayanecol** [comment]
Atribuída ao Luis a tarefa.

**Comment by veronicasvalerio** [comment]
Testado.
Falta ajustes.
Falta integração.

**Comment by dedeski** [comment]
### Definição:
Como usuário, quero poder redefinir a minha senha para continuar a acessar a ferramenta de Gerenciamento de tarefas em casos de esquecimento e/ou segurança (roubo de senha).

### Descrição:
Para que o usuário possa redefinir sua senha, é preciso que seja inserido o código de acesso recebido (via e-mail ou telefone, a escolha do usuário) no momento da solicitação de redefinição de senha, criando em seguida uma nova senha.

### Protótipo:
https://www.figma.com/file/cCdALGucKSuO1sa4BSUQww/Routinely?type=design&node-id=2-6074&mode=design

---
### Critérios de Aceite:

**Campo Código de Verificação:**

1. O campo Código de Verificação é obrigatório.
2. O campo Código de Verificação só poderá conter números.
3. O campo Código de Verificação terá 6 caracteres.

**Opção Enviar:**

1. A opção ‘Enviar’ só será habilitada quando o campo estiver corretamente preenchido, ou seja, com 6 dígitos. Caso o campo esteja preenchido incorretamente, a opção ‘Enviar’ permanecerá desabilitada.

**Opção Reenviar Código:**

1. Ao selecionar a opção ‘Reenviar código’, o usuário receber um novo código de verificação no dispositivo anteriormente escolhido (e-mail ou telefone).

**Opção Alterar Dispositivo de Verificação:**

1. Ao selecionar a opção ‘Alterar dispositivo de verificação’, o usuário retornará para o passo anterior (tela Esqueci a senha), onde poderá inserir um novo e-mail ou novo telefone para receber o código de verificação.

___
### Regras de Negócio

1. O código de verificação deverá conter 6 dígitos numéricos.
2. Se o sistema verificar que o código de verificação está incorreto, deverá exibir a mensagem: “O código de verificação que você inseriu não é válido. Verifique o código e tente novamente”.
3. Se o sistema verificar que o código de verificação está correto, o usuário deverá ser redirecionado para o próximo passo (tela Redefinição de senha).
