### ISSUE TITLE
Frontend - Esqueci a senha - Redefinir e reenviar senha - web

### ISSUE THREAD

**Issue by nickmoura** [RoutinelyOrganization/routinely-web#2]
https://docs.google.com/document/d/1tJMXDIZwOcnZkJbLA2W_xO4dQ3zpgINu/edit

## Alterar Senha - Como fazer ?

-  Crie uma função que pegue o usuário pelo ID
- Crie uma função que altere o dado { senha } no banco de dados com uma nova senha
-  Faça a função de alterar a senha ( Não se preocupar com email nem autentição, puramente a função )

- Lembre-se de usar as mesmas tratações da senha normal!

static async TrocarSenha() { 

const newPass = req.body.newPass

const id = req.body.id

const user = usermodel.find(id)

const newuser = {
pass : newPass
}

try{
 usermodel.save(newuser, where id = id)
}

}

**Comment by dayanecol** [comment]
Atribuída ao Guilherme a tarefa.

**Comment by huilianni** [comment]
@lilianekassab falta inserir as evidências.

**Comment by lilianekassab** [comment]
Segue evidências de teste [Frontend - Esqueci a senha - Redefinir e reenviar senha - web#2

[\[EVT\] Esqueci senha #2.docx](https://github.com/RoutinelyOrganization/routinely-web/files/12389165/EVT.Esqueci.senha.2.docx)

**Comment by veronicasvalerio** [comment]
Testou funcionalidade.
Falta integração.

**Comment by dedeski** [comment]
### Definição:
Como usuário, quero poder redefinir a minha senha para continuar a acessar a ferramenta de Gerenciamento de tarefas em casos de esquecimento e/ou segurança (roubo de senha).

### Descrição:
Para que o usuário possa redefinir sua senha, é preciso que seja inserido o código de acesso recebido (via e-mail ou telefone, a escolha do usuário) no momento da solicitação de redefinição de senha, criando em seguida uma nova senha.

### Protótipo:
https://www.figma.com/file/cCdALGucKSuO1sa4BSUQww/Routinely?type=design&node-id=2-6074&mode=design

---
**Critérios de Aceitação:**
* Todos os campos são obrigatórios.

**Campo E-mail ou Telefone:**

1. O usuário deve inserir no campo “E-mail ou telefone” a opção desejada para o envio do código de verificação;
    * Caso usuário tenha escolhido a opção “E-mail”, o sistema deverá enviar um código de verificação por e-mail.
    * Caso usuário tenha escolhido a opção “Telefone”, o sistema deverá enviar um código de verificação para o telefone.
2. O campo e-mail deve ser válido, seguindo a estrutura “user@domínio”. Ao selecionar a opção "Redefinir senha”, caso o e-mail digitado esteja em um formato inválido, o sistema deverá exibir a mensagem “E-mail inválido. Por favor, entre com um e-mail válido.”.

__Estrutura do e-mail:

Olá, <nome do usuário>!
Recebemos uma solicitação para redefinir a senha de sua conta Routinely.

<Código de verificação>

Insira este código para concluir o processo e criar uma nova senha.
Obrigada por nos ajudar a manter sua conta segura.

Equipe Routinely_

_Estrutura da mensagem por telefone:

Seu código de verificação de acesso para o Routinely é: <Código de verificação>__

---
### Regras de negócio:

1. Ao selecionar a opção “Redefinir senha”, o sistema deverá enviar um código de verificação para o usuário no dispositivo informado (e-mail ou telefone).
2. Caso o sistema identifique que um dos campos obrigatórios não está preenchido, o sistema não executará a ação e deverá exibir a seguinte mensagem abaixo do campo: “Campo de preenchimento obrigatório.”
