### ISSUE TITLE
Frontend - Criar Conta - web

### ISSUE THREAD

**Issue by nickmoura** [RoutinelyOrganization/routinely-web#3]
https://docs.google.com/document/d/1aJ_j1xtkFcDyY-aBpdVbGYJ14XhDTHRN/edit

**Comment by dayanecol** [comment]
- Criar uma página para criação de conta `SignUpPage`
name, email,  username, confirmpassword , password

- Criar o componente `Logo`
- Criar a imagem svg do ícone da logo `ImageLogo`
- Criar o componente `Header`
- Criar o componente `SignUpForm`
- Criar componente `ButtonBackPage`
- Criar o componente `Input`
- Criar o componente `Button`
- Criar o componente `ButtonSocial`
- Criar a imagem svg do ícone do Google `IconGoogle`
- Criar o componente `TermsOfUse`
- Criar o componente `LinkAuth`
- Criar o componente `ImageAuth`
- Criar a imagem svg da página de criação de conta `ImageSignUp`
- Criar o componente `TitleAuth`
- Criar o componente `SubTitleAuth`

**Comment by dayanecol** [comment]
Atribuída ao Guilherme a tarefa.

**Comment by huilianni** [comment]
@lilianekassab Falta inserir as evidências.

**Comment by lilianekassab** [comment]
Segue as evidências de testes do Frontend - Criar Conta - web#3

[\[EVT\] Criar Conta #3.docx](https://github.com/RoutinelyOrganization/routinely-web/files/12389112/EVT.Criar.Conta.3.docx)

**Comment by veronicasvalerio** [comment]
Testou funcionalidade
Falta integração

**Comment by dedeski** [comment]
### Definição:
Como um novo usuário, quero poder criar uma conta no Routinely para poder usar todos os recursos do produto.

### Descrição:
Para que o usuário tenha acesso aos recursos da ferramenta de gestão de tempo é preciso que o mesmo crie uma conta de usuário. Para isto faz-se necessário que os campos obrigatórios sejam preenchidos corretamente e que os termos de uso e política de privacidade sejam aceitos pelo usuário.

### Protótipo:
https://www.figma.com/file/cCdALGucKSuO1sa4BSUQww/Routinely?type=design&node-id=2-6074&mode=design

---
### Critérios de Aceite:
* Todos os campos são de preenchimento obrigatório;

**Campo Nome:**

1. O campo Nome não pode conter números.
2. O campo Nome deverá permitir os caracteres ' e - .
3. O campo Nome deve conter ao menos 3 caracteres. Ao clicar em criar, caso o nome digitado contenha menos de 3 caracteres o sistema deve exibir a mensagem "O nome deve conter ao menos 3 caracteres".

**Campo Senha:**

1. A senha deverá conter no mínimo 6 dígitos e ser composta por letras maiúsculas, letras minúsculas, números e caracteres especiais.
2. Ao digitar a senha, caso a mesma não esteja dentro dos critérios estabelecidos, o sistema deve exibir a seguinte mensagem: “A senha deve ter o mínimo de 6 dígitos e conter letras maiúsculas e minúsculas, números e símbolos como ! @ # $ % & * =”.
3. O campo Senha deve permitir ao usuário a opção de visualizar ou não a senha enquanto é digitada. Ao optar por não visualizar a digitação, a senha deverá ser apresentada através de “********”. Ao optar por visualizar a digitação, a senha digitada é exibida no campo.

**Campo Confirmar Senha:**

1. O conteúdo do campo Confirmar Senha deve ser igual ao do campo Senha. Caso o conteúdo do campo Confirmar Senha seja diferente do campo Senha, o sistema deverá exibir a mensagem “O campo Confirmar Senha deve ser igual ao campo Senha.”
2. O campo Confirmar Senha deve permitir ao usuário a opção de visualizar ou não a senha enquanto é digitada. Ao optar por não visualizar a digitação, a senha deverá ser apresentada através de “********”. Ao optar por visualizar a digitação, a senha digitada é exibida no campo.

**Campo E-mail:**

1. O campo e-mail deve ser válido, seguindo a estrutura “user@domínio”. Ao selecionar a opção "Criar Conta”, caso o e-mail digitado esteja em um formato inválido, o sistema deverá exibir a mensagem “E-mail inválido. Por favor, entre com um e-mail válido.”.
2. Não poderá haver duplicidade de e-mails. Caso o usuário tente utilizar um e-mail já cadastrado, o sistema deverá retornar a mensagem “Esse e-mail já está sendo utilizado.”

**Campo Termos de Uso e Política de Privacidade:**

1. O campo de Termos de Uso e Política de Privacidade será link, que deve direcionar o usuário para o respectivo documento;
2. O usuário deve ser capaz de visualizar a declaração de termos de uso e política de privacidade, ao clicar no link; Routinely - Termos e condições US1.docx
3. A declaração de termos de uso e política de privacidade deve aparecer para web em uma nova aba, sendo possível que o usuário clique em fechar para sair da tela e para o mobile deve direcionar para um navegador

_Estrutura do e-mail:

Assunto: Criação de Conta Routinely
Mensagem:
Seja Bem vindo (a) ao Routinely!
Sua conta foi criada com sucesso. Para ativá-la, confirme o seu endereço de e-mail clicando no link abaixo.
Link de confirmação._

---
### Regras de negócio

1. Caso o sistema identifique que um dos campos obrigatórios não está preenchido, o sistema não concluirá a criação da conta e exibirá a seguinte mensagem abaixo do campo: “Campo de preenchimento obrigatório.”
2. Ao selecionar a opção 'Criar Conta', estando todas as informações obrigatórias preenchidas e válidas, o sistema deverá enviar ao usuário um e-mail confirmando a criação da conta.
3. Ao selecionar a opção 'Criar conta', caso o checkbox 'De acordo' do campo Termo de Uso e Política de Privacidade não esteja selecionado, a conta não será criada. Nesse caso, o sistema deverá exibir a mensagem: "Você deve aceitar os Termos de Uso e Política de Privacidade para poder criar uma conta."
