### ISSUE TITLE
Frontend - Autenticar usuário - web

### ISSUE THREAD

**Issue by nickmoura** [RoutinelyOrganization/routinely-web#4]
https://docs.google.com/document/d/1Y1FBWvcw2kvFnTb2ZgDXaNwUBVmUwvEg/edit

## Login Usuário - Como fazer??

- Capture o Email e a senha pelo req.body
- valide e trate essas informações ( com criptografia e validação de caracteres)
- use a função de retornar o usuário pelo email e pegue o user
- verifique se a senha bate
- se sucesso -> Logado
- trate cada erro com uma resposta diferente

**Comment by paulomarinato** [comment]
Ciente.

**Comment by dayanecol** [comment]
Atribuída ao Luis a tarefa.

**Comment by huilianni** [comment]
@carol-schmidt falta testar o layout.

**Comment by lilianekassab** [comment]
Segue os testes acessar conta.[Frontend - Autenticar usuário - web#4]

[acessar conta.docx](https://github.com/RoutinelyOrganization/routinely-web/files/12389124/acessar.conta.docx)

**Comment by veronicasvalerio** [comment]
Falta integração.
